In [11]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)

# Print the tensor
print(random_tensor)


tensor([[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388],
        [0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399],
        [0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893],
        [0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770],
        [0.4108, 0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189],
        [0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658],
        [0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451, 0.4966]])


In [12]:

# Tensor from exercise 2
tensor1 = torch.rand(7, 7)

# Create another random tensor with shape (1, 7)
tensor2 = torch.rand(1, 7)

# Transpose it to make matrix multiplication possible
tensor2_T = tensor2.T  # Now shape becomes (7, 1)

# Perform matrix multiplication
result = torch.matmul(tensor1, tensor2_T)

print("Tensor 1 shape:", tensor1.shape)
print("Tensor 2 shape:", tensor2.shape)
print("Tensor 2 Transposed shape:", tensor2_T.shape)
print("Result shape:", result.shape)
print(result)


Tensor 1 shape: torch.Size([7, 7])
Tensor 2 shape: torch.Size([1, 7])
Tensor 2 Transposed shape: torch.Size([7, 1])
Result shape: torch.Size([7, 1])
tensor([[2.0983],
        [1.8557],
        [1.4832],
        [1.5734],
        [1.7670],
        [2.4643],
        [1.4786]])


In [13]:

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Transpose the second tensor
tensor2_T = tensor2.T

# Matrix multiply tensors
result = torch.matmul(tensor1, tensor2_T)

print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


In [14]:

# Set random seed for CPU
torch.manual_seed(0)

# Set random seed on the GPU
torch.cuda.manual_seed(1234)


In [15]:

# Set random seed for reproducibility
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Create two random tensors on the GPU
tensor_A = torch.rand(2, 3, device=device)
tensor_B = torch.rand(2, 3, device=device)

print(tensor_A, tensor_B)


Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


In [16]:
# Set random seed
torch.manual_seed(1234)

# Select device (GPU if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Create two random tensors on the GPU
tensor_A = torch.rand(2, 3, device=device)
tensor_B = torch.rand(2, 3, device=device)

# Perform matrix multiplication
# tensor_A is (2, 3), so we need tensor_B.T to be (3, 2)
result = torch.matmul(tensor_A, tensor_B.T)

print(result, result.shape)

Device: cpu
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


In [17]:
# Find max
max_value = result.max()

# Find min
min_value = result.min()

print("Maximum value:", max_value)
print("Minimum value:", min_value)


Maximum value: tensor(0.5617)
Minimum value: tensor(0.3647)


In [18]:
# Find arg max
arg_max = result.argmax()

# Find arg min
arg_min = result.argmin()

print("Index of max value:", arg_max)
print("Index of min value:", arg_min)


Index of max value: tensor(3)
Index of min value: tensor(0)


In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor with shape (1, 1, 1, 10)
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions using squeeze()
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
